### ISSUE TITLE
Use directive to start simulation

### ISSUE THREAD

**Issue by c-martinez** [indodutch/sim-city-cs#1]
@blootsvoets , sorry it has taken me soooo long to get something back to you, but I have something sort of demo able.

Can we meet quickly to touch base on this?

```
$ git clone git@github.com:NLeSC/sim-city-cs.git
$ cd sim-city-cs/
$ git checkout master
$ npm i
$ cd public/
$ bower i
$ cd ../
$ tsc -p .
$ node server.js
```

**Comment by blootsvoets** [comment]
Start simulation works, per #21.
