### ISSUE TITLE
add all relevant output files as layers

### ISSUE THREAD

**Issue by blootsvoets** [indodutch/sim-city-cs#16]
See #2, create buttons or a widget for each simulation, that you can click to show some output or input features, and apply a styling.

**Comment by bpmweel** [comment]
- Show output button should insert all output files as layers 
- Show message that this has been done.

**Comment by bpmweel** [comment]
- Message would be nice to have a 'Switch to Home' button, or 'Click to view'

**Comment by bpmweel** [comment]
- Decided to remove the Simulation management dashboard, so switching to home should not be necessary
