### ISSUE TITLE
Move Simulation Form to Widget

### ISSUE THREAD

**Issue by bpmweel** [indodutch/sim-city-cs#23]
- [x] Simulation List to have a ´Create Simulation' button.
- [x] Move simulation list to Home Dashboard
- [x] Remove Simulation Management Dashboard.
- [x] Admin widget in settings tab.

**Comment by blootsvoets** [comment]
Fixed style and actually create a simulation when the create simulation button is pressed.

**Comment by bpmweel** [comment]
Form now works again, in a separate widget. Closing the widget is done through ng-hide, but it's a little slow and needs to be looked at

**Comment by bpmweel** [comment]
Slow closing has been fixed by removing the dependency on ngAnimate.
