### ISSUE TITLE
Simulation form buggy

### ISSUE THREAD

**Issue by blootsvoets** [indodutch/sim-city-cs#36]
- [x] Clicking anywhere in the simulation form makes it dark on click
- [x] The validation message for feature lists is only shown once a feature has been added or removed
- [x] When dragging a feature in, it appears in the list as lat-lon. When clicking "save" it appears double, once with a name. Clicking "remove" only affects the one with the name, the one with only lat-lon remains present. Moving the feature does not affect the lat-lon version.
- [x] Cancel button is broken

Tested on Safari Technology Preview and Chrome

**Comment by bpmweel** [comment]
Clicking turning the form dark came from using the button-container class. Now using from-container with copied css.
